config/routes.rb
Rails.application.routes.draw do
  resources :temperatures
  resources :sensors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sensor.rb
class Sensor < ApplicationRecord
  has_many :temperatures
  validates :device, presence: true
end

app/models/temperature.rb
class Temperature < ApplicationRecord
  belongs_to :sensor
  validates :sensor_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_action :set_sensor, only: [:show, :edit, :update, :destroy]

  # GET /sensors
  # GET /sensors.json
  def index
    @sensors = Sensor.all
  end

  # GET /sensors/1
  # GET /sensors/1.json
  def show
  end

  # GET /sensors/new
  def new
    @sensor = Sensor.new
  end

  # GET /sensors/1/edit
  def edit
  end

  # POST /sensors
  # POST /sensors.json
  def create
    @sensor = Sensor.new(sensor_params)

    respond_to do |format|
      if @sensor.save
        format.html { redirect_to @sensor, notice: 'Sensor was successfully created.' }
        format.json { render :show, status: :created, location: @sensor }
      else
        format.html { render :new }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sensors/1
  # PATCH/PUT /sensors/1.json
  def update
    respond_to do |format|
      if @sensor.update(sensor_params)
        format.html { redirect_to @sensor, notice: 'Sensor was successfully updated.' }
        format.json { render :show, status: :ok, location: @sensor }
      else
        format.html { render :edit }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1
  # DELETE /sensors/1.json
  def destroy
    @sensor.destroy
    respond_to do |format|
      format.html { redirect_to sensors_url, notice: 'Sensor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sensor
      @sensor = Sensor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sensor_params
      params.require(:sensor).permit(:device)
    end
end

app/controllers/temperatures_controller.rb
class TemperaturesController < ApplicationController
  before_action :set_temperature, only: [:show, :edit, :update, :destroy]

  # GET /temperatures
  # GET /temperatures.json
  def index
    @temperatures = Temperature.all
  end

  # GET /temperatures/1
  # GET /temperatures/1.json
  def show
  end

  # GET /temperatures/new
  def new
    @temperature = Temperature.new
  end

  # GET /temperatures/1/edit
  def edit
  end

  # POST /temperatures
  # POST /temperatures.json
  def create
    @temperature = Temperature.new(temperature_params)

    respond_to do |format|
      if @temperature.save
        format.html { redirect_to @temperature, notice: 'Temperature was successfully created.' }
        format.json { render :show, status: :created, location: @temperature }
      else
        format.html { render :new }
        format.json { render json: @temperature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /temperatures/1
  # PATCH/PUT /temperatures/1.json
  def update
    respond_to do |format|
      if @temperature.update(temperature_params)
        format.html { redirect_to @temperature, notice: 'Temperature was successfully updated.' }
        format.json { render :show, status: :ok, location: @temperature }
      else
        format.html { render :edit }
        format.json { render json: @temperature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /temperatures/1
  # DELETE /temperatures/1.json
  def destroy
    @temperature.destroy
    respond_to do |format|
      format.html { redirect_to temperatures_url, notice: 'Temperature was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_temperature
      @temperature = Temperature.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def temperature_params
      params.require(:temperature).permit(:sensor_id, :temp, :day, :at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/helpers/temperatures_helper.rb
module TemperaturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LesterbotToy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sensors/_form.html.erb
<%= form_with(model: sensor, local: true) do |form| %>
  <% if sensor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sensor.errors.count, "error") %> prohibited this sensor from being saved:</h2>

      <ul>
      <% sensor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :device %>
    <%= form.text_field :device, id: :sensor_device %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sensors/edit.html.erb
<h1>Editing Sensor</h1>

<%= render 'form', sensor: @sensor %>

<%= link_to 'Show', @sensor %> |
<%= link_to 'Back', sensors_path %>

app/views/sensors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sensors</h1>

<table>
  <thead>
    <tr>
      <th>Device</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sensors.each do |sensor| %>
      <tr>
        <td><%= sensor.device %></td>
        <td><%= link_to 'Show', sensor %></td>
        <td><%= link_to 'Edit', edit_sensor_path(sensor) %></td>
        <td><%= link_to 'Destroy', sensor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sensor', new_sensor_path %>

app/views/sensors/new.html.erb
<h1>New Sensor</h1>

<%= render 'form', sensor: @sensor %>

<%= link_to 'Back', sensors_path %>

app/views/sensors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Device:</strong>
  <%= @sensor.device %>
</p>

<%= link_to 'Edit', edit_sensor_path(@sensor) %> |
<%= link_to 'Back', sensors_path %>

app/views/temperatures/_form.html.erb
<%= form_with(model: temperature, local: true) do |form| %>
  <% if temperature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(temperature.errors.count, "error") %> prohibited this temperature from being saved:</h2>

      <ul>
      <% temperature.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sensor_id %>
    <%= form.number_field :sensor_id, id: :temperature_sensor_id %>
  </div>

  <div class="field">
    <%= form.label :temp %>
    <%= form.text_field :temp, id: :temperature_temp %>
  </div>

  <div class="field">
    <%= form.label :day %>
    <%= form.date_select :day, id: :temperature_day %>
  </div>

  <div class="field">
    <%= form.label :at %>
    <%= form.time_select :at, id: :temperature_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/temperatures/edit.html.erb
<h1>Editing Temperature</h1>

<%= render 'form', temperature: @temperature %>

<%= link_to 'Show', @temperature %> |
<%= link_to 'Back', temperatures_path %>

app/views/temperatures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Temperatures</h1>

<table>
  <thead>
    <tr>
      <th>Sensor</th>
      <th>Temp</th>
      <th>Day</th>
      <th>At</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @temperatures.each do |temperature| %>
      <tr>
        <td><%= temperature.sensor_id %></td>
        <td><%= temperature.temp %></td>
        <td><%= temperature.day %></td>
        <td><%= temperature.at %></td>
        <td><%= link_to 'Show', temperature %></td>
        <td><%= link_to 'Edit', edit_temperature_path(temperature) %></td>
        <td><%= link_to 'Destroy', temperature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Temperature', new_temperature_path %>

app/views/temperatures/new.html.erb
<h1>New Temperature</h1>

<%= render 'form', temperature: @temperature %>

<%= link_to 'Back', temperatures_path %>

app/views/temperatures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sensor:</strong>
  <%= @temperature.sensor_id %>
</p>

<p>
  <strong>Temp:</strong>
  <%= @temperature.temp %>
</p>

<p>
  <strong>Day:</strong>
  <%= @temperature.day %>
</p>

<p>
  <strong>At:</strong>
  <%= @temperature.at %>
</p>

<%= link_to 'Edit', edit_temperature_path(@temperature) %> |
<%= link_to 'Back', temperatures_path %>